#[Info]
site_name: 图拉丁入门手册 #网站名字
site_url: http://docs.tualatin.club #网站地址
site_author: R3默秒全 #作者名

#[UI]

theme:
  name: material
  language: zh 
  palette:
    scheme: slate


copyright: Copyright @ 2022 Tualatin CLUB # 左下角的版权声明

nav:
    - 'index.md'
    - 'win.md'
    - 'sys.md'
#    - 'CPU.md'
#    - 'motherboard.md'
#    - 'mem.md'
#    - 'GPU.md'
    - 'disk.md'
#    - 'monitor.md'
#    - 'device.md'
#    - 'stress.md'
#    - 'others.md'
    - 'Q&A.md'

plugins:
  - search:
      separator: '[\s\u200b\-]'

  
